// Compile the core components to plain JS, and commit the result.
//
// The package used to ship raw .jsx and rely on every consumer listing it in
// `transpilePackages`. That works until it doesn't: on DollarDeploy's build
// infrastructure Next silently declines to transpile it, and the build fails
// with "Module parse failed: Unexpected token" pointing at a `<div`. The same
// commit, the same Node and the same npm build correctly on a laptop and on the
// deployment host — so the consumer has no way to fix it and no way to see why.
//
// Shipping compiled JS removes the requirement instead of working around it.
// Consumers keep `transpilePackages` harmlessly if they already have it, and
// new ones need nothing.
//
// The output is COMMITTED, not built on install. The package is consumed over a
// git URL, so a `prepare` step would have to run on the consumer's builder —
// which is exactly the environment that cannot be relied on, and which omits
// devDependencies under `production=true`.

import { build } from 'esbuild';
import { readFile, writeFile, mkdir } from 'node:fs/promises';

const pkg = JSON.parse(await readFile('package.json', 'utf8'));

await mkdir('dist', { recursive: true });

await build({
    entryPoints: ['components/core/index.js'],
    outfile: 'dist/index.js',
    bundle: true,
    format: 'esm',
    platform: 'browser',
    target: ['es2022'],
    jsx: 'automatic',
    loader: { '.jsx': 'jsx' },
    // React stays a peer dependency — bundling it would give every consumer a
    // second copy and break hooks.
    external: ['react', 'react-dom', 'react/jsx-runtime'],
    legalComments: 'none',
    banner: { js: `// @misterbeardy/design-system ${pkg.version} — generated by build.mjs, do not edit.` },
});

const out = await readFile('dist/index.js', 'utf8');
if (/<[A-Za-z]/.test(out.replace(/\/\/.*$/gm, ''))) {
    throw new Error('dist/index.js still contains JSX — the transform did not run.');
}
console.log(`dist/index.js written (${(out.length / 1024).toFixed(1)} kB)`);
